<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\TSD.BulkExtensions.PostgreSql\TSD.BulkExtensions.PostgreSql.csproj" />
    <ProjectReference Include="..\TSD.BulkExtensions.Tests.Shared\TSD.BulkExtensions.Tests.Shared.csproj" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

</Project>
